<#
.SYNOPSIS
  Deploy the iPhone Backup Manager staging bundle to a target machine folder.

.DESCRIPTION
  Copies the app from the staging directory to a deployment path, stores runtime
  config outside the bundle, bootstraps Python dependencies, and optionally
  installs the Windows service.

.EXAMPLE
  .\deploy.ps1 -TargetPath "D:\Apps\iPhoneManager"

.EXAMPLE
  .\deploy.ps1 -TargetPath "C:\Program Files\iPhoneManager" -ConfigDir "D:\Data\iPhoneManager\config" -InstallService
#>

[CmdletBinding()]
param(
    [Parameter()][string]$TargetPath,
    [Parameter()][string]$ConfigDir = "",
    [switch]$InstallService,
    [switch]$Clean,
    [switch]$SkipPythonSetup
)

$ErrorActionPreference = "Stop"

$StagingRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$BackendDir  = Join-Path $StagingRoot "backend"

function Write-Step([string]$Message) {
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Ensure-Directory([string]$Path) {
    if (-not (Test-Path $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

if (-not $TargetPath) {
    $defaultTarget = Join-Path $env:LOCALAPPDATA "Programs\iPhoneManager"
    $TargetPath = Read-Host "Deployment folder [$defaultTarget]"
    if ([string]::IsNullOrWhiteSpace($TargetPath)) {
        $TargetPath = $defaultTarget
    }
}

$TargetPath = [System.IO.Path]::GetFullPath($TargetPath)

if (-not $ConfigDir) {
    $defaultConfig = Join-Path $env:APPDATA "iPhoneManager"
    $ConfigDir = Read-Host "Config folder [$defaultConfig]"
    if ([string]::IsNullOrWhiteSpace($ConfigDir)) {
        $ConfigDir = $defaultConfig
    }
}

$ConfigDir = [System.IO.Path]::GetFullPath($ConfigDir)
$ExampleConfig = Join-Path $BackendDir "config.example.json"
$TargetConfig  = Join-Path $ConfigDir "config.json"

Write-Host ""
Write-Host "iPhone Backup Manager deployment" -ForegroundColor Green
Write-Host "  From:   $StagingRoot"
Write-Host "  To:     $TargetPath"
Write-Host "  Config: $TargetConfig"
Write-Host ""

if ($TargetPath.TrimEnd('\') -eq $StagingRoot.TrimEnd('\')) {
    throw "TargetPath must be different from the staging folder."
}

Ensure-Directory $TargetPath
Ensure-Directory $ConfigDir

Write-Step "Copying application files"
$robocopyArgs = @(
    $StagingRoot,
    $TargetPath,
    "/E",
    "/NFL", "/NDL", "/NJH", "/NJS", "/NC", "/NS",
    "/XD", "logs", ".git", ".venv", "__pycache__",
    "/XF", "config.json"
)

if ($Clean) {
    $robocopyArgs += "/MIR"
}

$copy = Start-Process -FilePath "robocopy.exe" -ArgumentList $robocopyArgs -Wait -PassThru -NoNewWindow
if ($copy.ExitCode -gt 8) {
    throw "File copy failed with robocopy exit code $($copy.ExitCode)"
}

Write-Step "Writing deployment environment"
$EnvironmentPs1 = Join-Path $TargetPath "environment.ps1"
$EnvironmentCmd = Join-Path $TargetPath "environment.cmd"
@(
    "# Generated by deploy.ps1 on $(Get-Date -Format s)",
    "`$env:IPHONE_MANAGER_CONFIG_DIR = '$($ConfigDir.Replace("'", "''"))'"
) | Set-Content -Path $EnvironmentPs1 -Encoding UTF8

@(
    "@echo off",
    "set IPHONE_MANAGER_CONFIG_DIR=$ConfigDir"
) | Set-Content -Path $EnvironmentCmd -Encoding ASCII

$StartScript = Join-Path $TargetPath "Start-iPhoneManager.ps1"
@(
    "`$ProjectRoot = Split-Path -Parent `$MyInvocation.MyCommand.Path",
    ". `"`$ProjectRoot\environment.ps1`"",
    "& `"`$ProjectRoot\launch.ps1`""
) | Set-Content -Path $StartScript -Encoding UTF8

$StartBat = Join-Path $TargetPath "Start-iPhoneManager.bat"
@(
    "@echo off",
    "setlocal",
    "cd /d `"%~dp0`"",
    "if exist environment.cmd call environment.cmd",
    "call start.bat"
) | Set-Content -Path $StartBat -Encoding ASCII

if (-not (Test-Path $TargetConfig)) {
    Write-Step "Creating initial config file"
    if (-not (Test-Path $ExampleConfig)) {
        throw "Missing template: $ExampleConfig"
    }
    Copy-Item $ExampleConfig $TargetConfig
} else {
    Write-Host "Keeping existing config: $TargetConfig" -ForegroundColor Yellow
}

if (-not $SkipPythonSetup) {
    Write-Step "Installing Python dependencies"
    $TargetBackend = Join-Path $TargetPath "backend"
    $Python = Get-Command python -ErrorAction Stop
    $VenvPath = Join-Path $TargetBackend ".venv"

    if (-not (Test-Path $VenvPath)) {
        & $Python.Source -m venv $VenvPath
    }

    $Pip = Join-Path $VenvPath "Scripts\pip.exe"
    $Req = Join-Path $TargetBackend "requirements.txt"
    & $Pip install -r $Req -q
}

Ensure-Directory (Join-Path $TargetPath "logs")

if ($InstallService) {
    Write-Step "Installing Windows service"
    $InstallScript = Join-Path $TargetPath "install_service.ps1"
    if (-not (Test-Path $InstallScript)) {
        throw "Missing install script in deployment target: $InstallScript"
    }
    & $InstallScript
}

Write-Host ""
Write-Host "Deployment complete." -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Start the app:"
Write-Host "       $StartBat"
Write-Host "  2. Open http://127.0.0.1:5055"
Write-Host "  3. Complete the first-run setup wizard"
Write-Host "  4. Enter the backup path and test it before using backups"
Write-Host ""
Write-Host "Runtime config file:"
Write-Host "  $TargetConfig"
Write-Host ""
